apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: locationtracker
  labels:
    app: locationtracker
spec:
  clusterIP: None
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
    protocol: TCP
  - name: "8081"
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: locationtracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locationtracker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: locationtracker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: locationtracker
    spec:
      containers:
      - image: rbackhouse/locationtracker:v1
        imagePullPolicy: IfNotPresent
        name: locationtracker
        command: ["/bin/locationtracker"]
        env:
        - name: LOG_LEVEL
          value: info
        - name: REDIS_URL
          value: redis:6379
        ports:
        - containerPort: 8082
        - containerPort: 8081
        volumeMounts:
        - name: locationtracker-config
          mountPath: /data
      volumes:
      - name: locationtracker-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontenvoy
  labels:
    app: frontenvoy
    service: frontenvoy
spec:
  selector:
    app: frontenvoy
  ports:
  - name: grpchttps
    port: 9443
    targetPort: 9443
    protocol: TCP
  - name: wshttps
    port: 9444
    targetPort: 9444
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenvoy-v1
  labels:
    app: frontenvoy
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontenvoy
      version: v1
  template:
    metadata:
      labels:
        app: frontenvoy
        version: v1
    spec:
      containers:
      - name: frontenvoy
        image: rbackhouse/frontenvoy_tls:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: loglevel
          value: debug
        ports:
        - containerPort: 9443
        - containerPort: 9444
---
apiVersion: v1
kind: Service
metadata:
  name: ltweb
  labels:
    app: ltweb
spec:
  clusterIP: None
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: ltweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltweb-v1
  labels:
    app: ltweb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ltweb
      version: v1
  template:
    metadata:
      labels:
        app: ltweb
        version: v1
    spec:
      containers:
      - name: ltweb
        image: rbackhouse/ltweb:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
